export const ADMIN_ROUTE = "/admin"
export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const SITE_ROUTE = "/"
export const COURSES_ROUTE = "/courses"
export const COURSE_ROUTE = "/course"